<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>Async await with Error</title>
  </head>
  <body>
    <script>
      async function getRepository() {
        try {
        const repositorys = await fetch('https://api.github.com/users/mayconbalves/repos?per_page=50')
        const data = await repositorysss.json()
        // Usando catch pra pegar possível erros na hora de fazer a requisição
        // O erro está no repositorysss.json- o correto é repositorys
        } catch (err) {
          console.error('Ops', err)
        }
      }

      getRepository()
    </script>
  </body>
</html>

